# version: "3.9"

services:
  backend:
    build:
      context: ./back
    container_name: emotion_backend
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app         # ðŸ‘ˆ Synchronise ton code local avec le conteneur
    environment:
      - FLASK_ENV=development   # ðŸ‘ˆ Active le mode auto-reload Flask
    command: flask run --host=0.0.0.0 --port=5000

  frontend:
    build:
      context: ./front
    container_name: emotion_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app            # ðŸ‘ˆ Synchronise ton code local avec le conteneur
      - /app/node_modules       # ðŸ‘ˆ EmpÃªche les conflits node_modules
    environment:
      - NODE_ENV=development    # ðŸ‘ˆ Active le hot reload de Next.js
    command: npm run dev        # ðŸ‘ˆ DÃ©marre Next.js en mode dev
